[2023-01-04 02:17:55,348] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2023-01-04 02:17:55,355] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2023-01-04 02:17:55,355] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 02:17:55,355] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 02:17:55,355] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 02:17:55,370] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2023-01-02 07:00:00+00:00
[2023-01-04 02:17:55,374] {standard_task_runner.py:52} INFO - Started process 47940 to run task
[2023-01-04 02:17:55,492] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2023-01-02T07:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpgor7typo', '--error-file', '/tmp/tmpdy8tdmyh']
[2023-01-04 02:17:55,493] {standard_task_runner.py:80} INFO - Job 19: Subtask get_crypto_values
[2023-01-04 02:17:55,656] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 02:17:56,214] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T07:00:00+00:00
[2023-01-04 02:17:58,659] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/xuxon/Documents/airflow_case/dags/populate_crypto_values.py", line 73, in get_crypto_values_func
    errors = client.insert_rows_json('data-case-study-322621.renan.test_table_crypto', price_dict_list)
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3666, in insert_rows_json
    response = self._call_api(
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 789, in _call_api
    return call()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/data-case-study-322621/datasets/renan/tables/test_table_crypto/insertAll?prettyPrint=false: No rows present in the request.
[2023-01-04 02:17:58,752] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20230102T070000, start_date=20230104T051755, end_date=20230104T051758
[2023-01-04 02:17:58,788] {standard_task_runner.py:92} ERROR - Failed to execute job 19 for task get_crypto_values (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/data-case-study-322621/datasets/renan/tables/test_table_crypto/insertAll?prettyPrint=false: No rows present in the request.; 47940)
[2023-01-04 02:17:58,837] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-04 02:17:58,877] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 14:09:23,034] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2023-01-04 14:09:23,051] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [queued]>
[2023-01-04 14:09:23,051] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:09:23,051] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 14:09:23,051] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:09:23,064] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2023-01-02 07:00:00+00:00
[2023-01-04 14:09:23,069] {standard_task_runner.py:52} INFO - Started process 34334 to run task
[2023-01-04 14:09:23,074] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2023-01-02T07:00:00+00:00', '--job-id', '792', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp1hap0acm', '--error-file', '/tmp/tmpwpc5mm6h']
[2023-01-04 14:09:23,075] {standard_task_runner.py:80} INFO - Job 792: Subtask get_crypto_values
[2023-01-04 14:09:23,127] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 14:09:23,195] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T07:00:00+00:00
[2023-01-04 14:09:24,625] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 14:09:24,626] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 14:09:24,647] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20230102T070000, start_date=20230104T170923, end_date=20230104T170924
[2023-01-04 14:09:24,682] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 14:09:24,702] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
